pr:
 branches:
   exclude:
    - releases/*
    - master
    - develop
    - dependabot/*
trigger:
  branches:
    exclude:
      - releases/*
      - master
      - develop
      - dependabot/*
pool:
  vmImage: 'Windows-2019'
jobs:
  - job: Build
    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
      my_build_number: ''
    displayName: 'Build solution and create NuGet packages'
    continueOnError: false
    workspace:
      clean: resources
    cancelTimeoutInMinutes: 5
    steps:
      - task: UseDotNet@2
        displayName: "Use .Net 5 sdk"
        inputs:
          packageType: sdk
          version: "5.0.100-rc.2.20479.15"
          includePreviewVersions: true
      - task: DotNetCoreCLI@2
        displayName: 'Build solution'
        inputs:
          command: 'build'
          projects: |
            $(solution)
          arguments: '--configuration $(buildConfiguration)'
          versioningScheme: off

      - task: PowerShell@2
        displayName: 'Create Nuget version'
        inputs:
          filePath: './scripts/version.ps1'
          arguments: '-BRANCH_NAME $(Build.SourceBranchName)'
      - task: PowerShell@2
        displayName: 'Create Nuget packages'
        inputs:
          filePath: './scripts/packall.ps1'
          arguments: '-VERSION $(my_build_number) -BUILD_ARTIFACT_DIR $(Build.ArtifactStagingDirectory)'

      - task: NuGetCommand@2
        continueOnError: false
        displayName: 'Push Nuget Packages'
        inputs:
          command: 'push'
          packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
          nuGetFeedType: 'external'
          publishFeedCredentials: 'Nuget.org'

      - task: GitHubRelease@1
        displayName: 'Create GitHub release'
        inputs:
          gitHubConnection: 'github.com_azpipelines'
          repositoryName: '$(Build.Repository.Name)'
          action: 'create'
          target: '$(Build.SourceVersion)'
          tagSource: 'userSpecifiedTag'
          tag: 'v$(my_build_number)'
          title: 'Version $(my_build_number)'
          releaseNotesSource: 'inline'
          releaseNotesInline: 'Changelog: https://github.com/LuccasGianesini/solari/wiki/Changelog'
          assets: false
          addChangeLog: true
