# Add person with invalid Name
POST http://localhost:5000/api/person
content-type: application/json

{
  "Name": ""
}
###

# Add person with valid Name
POST http://localhost:5000/api/person
content-type: application/json

{
  "Name": "Teste"
}

###

# Add attribute to person
POST http://localhost:5000/api/person/attributes
Content-Type: application/json

{
  "PersonId" : "5e6a8c494c889034f87ad71d",
  "AttributeName": "Stas",
  "AttributeValue": "true"
}

###
