apiVersion: v1
data:
  collector: |
    collector:
      zipkin:
        http-port: 9411
    cassandra:
      servers: cassandra
      keyspace: jaeger_v1_dc1
  query: |
    cassandra:
      servers: cassandra
      keyspace: jaeger_v1_dc1
  span-storage-type: cassandra
kind: ConfigMap
metadata:
  labels:
    app: jaeger
    jaeger-infra: configuration
  name: jaeger-configuration
  namespace: jaeger